### PR TITLE
public store method for other plugin use

### PR DESCRIPTION
**Pull request by dwlrathod**
This commit adds the ability for other plugins to save data with secure storage plugin and interact on webview.

### CODE REVIEW

**Comment by BorntraegerMarc** [comment]
To give some background: We have developed an own internal cordova plugin which uses this secure-storage plugin.

To interact with the secure-storage plugin we need this method to be public.

This way we can share secure storage data with our own plugin & our cordova app

**Comment by dwlrathod** [comment]
Friendly ping can this PR be reviewed? :)

**Comment by mibrito707** [comment]
Hey @dwlrathod 
Thanks for your contribution, I'll review this and and bundle it in the next release.

**Comment by BorntraegerMarc** [comment]
@mibrito707 any idea when the next release is scheduled for? 🙂

**Comment by mibrito707** [comment]
Couldn't resolve the merge conflicts because the original branch seems to be deleted, but this commit https://github.com/mibrito707/cordova-plugin-secure-storage-echo/commit/c441fe90d1c043a35eebf47533cfd42c36156e56 does exactly the same.

**Pull request closed without merging**
